# Generated by Django 2.2.6 on 2019-10-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_deduction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.ManyToManyField(blank=True, null=True, to='salaries.Deduction'),
        ),
    ]
