# Generated by Django 2.2.6 on 2019-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_auto_20191029_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='type',
            field=models.CharField(choices=[('benefit', 'Benefit'), ('loan', 'Loan')], default='benefit', max_length=200),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.ManyToManyField(blank=True, to='salaries.Deduction'),
        ),
    ]
