# Generated by Django 2.2.6 on 2019-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0005_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='type',
            field=models.CharField(choices=[('late', 'Late'), ('absent', 'absent')], default='late', max_length=200),
        ),
    ]
