# Generated by Django 2.2.6 on 2019-12-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0006_timerecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='period',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
